/**
 * Core type definitions for RCA Agent
 * 
 * This file contains all shared interfaces and types used throughout the system.
 * Following single source of truth principle for type definitions.
 */

/**
 * Parsed error information extracted from error text
 */
export interface ParsedError {
  /** Type of error (e.g., 'lateinit', 'npe', 'build') */
  type: string;
  
  /** Full error message */
  message: string;
  
  /** File where error occurred */
  filePath: string;
  
  /** Line number where error occurred (1-indexed) */
  line: number;
  
  /** Programming language */
  language: 'kotlin' | 'java' | 'xml' | 'gradle' | 'proguard';
  
  /** Optional: Framework/library (e.g., 'compose', 'android') - added in Chunk 4.1 */
  framework?: string;
  
  /** Optional: Column number */
  column?: number;
  
  /** Optional: Stack trace frames */
  stackTrace?: StackFrame[];
  
  /** Optional: Additional metadata specific to error type */
  metadata?: Record<string, any>;
}

/**
 * Stack trace frame information
 */
export interface StackFrame {
  /** File path */
  file: string;
  
  /** Line number */
  line: number;
  
  /** Function/method name */
  function?: string;
  
  /** Class name */
  className?: string;
}

/**
 * Root Cause Analysis result
 */
export interface RCAResult {
  /** Original error message */
  error: string;
  
  /** Identified root cause */
  rootCause: string;
  
  /** Step-by-step fix guidelines */
  fixGuidelines: string[];
  
  /** Confidence score (0-1) */
  confidence: number;
  
  /** Optional: Number of iterations taken (added in Chunk 2.4) */
  iterations?: number;
  
  /** Optional: Tools used during analysis (added in Chunk 2.4) */
  toolsUsed?: string[];
  
  /** Optional: Related code snippets */
  codeContext?: string;
  
  /** Optional: Similar past errors */
  similarErrors?: string[];
  
  /** Optional: Generated code fix with diff (added in Chunk 5) */
  codeFix?: CodeFix;
}

/**
 * Generated code fix with diff information (Chunk 5: Fix Generator)
 */
export interface CodeFix {
  /** File being fixed */
  filePath: string;
  
  /** Line number where fix applies */
  line: number;
  
  /** Original code (before fix) */
  originalCode: string;
  
  /** Fixed code (after fix) */
  fixedCode: string;
  
  /** Formatted diff (markdown or unified) */
  diff: string;
  
  /** Explanation of what changed and why */
  explanation: string;
  
  /** Confidence score (0-100) */
  confidence: number;
  
  /** Whether fix is syntactically valid */
  syntaxValid: boolean;
  
  /** Optional: Additional files that need changes */
  relatedFiles?: RelatedFileFix[];
}

/**
 * Fix for related files (e.g., Gradle + Kotlin)
 */
export interface RelatedFileFix {
  filePath: string;
  line: number;
  originalCode: string;
  fixedCode: string;
  explanation: string;
}

/**
 * Agent state during analysis
 * Used for tracking progress and enabling checkpoint/resume
 */
export interface AgentState {
  /** Current iteration number */
  iteration: number;
  
  /** Maximum iterations allowed */
  maxIterations: number;
  
  /** Start time (timestamp) */
  startTime: number;
  
  /** Timeout in milliseconds */
  timeout: number;
  
  /** Analysis mode */
  mode: 'standard' | 'educational' | 'fast';
  
  /** Thoughts generated by agent */
  thoughts: string[];
  
  /** Actions taken (tool calls) */
  actions: ToolCall[];
  
  /** Observations from tool executions */
  observations: string[];
  
  /** Current hypothesis */
  hypothesis: string | null;
  
  /** Identified root cause */
  rootCause: string | null;
  
  /** Whether analysis has converged */
  converged: boolean;
  
  /** Error being analyzed */
  error: ParsedError;
  
  /** Optional: File content at error location (added in Chunk 1.4) */
  fileContent?: string | null;
}

/**
 * Tool call made by agent
 */
export interface ToolCall {
  /** Tool name */
  tool: string;
  
  /** Parameters passed to tool */
  parameters: Record<string, any>;
  
  /** Timestamp when tool was called */
  timestamp: number;
  
  /** Optional: Result of tool execution */
  result?: any;
  
  /** Optional: Error if tool failed */
  error?: string;
}

/**
 * LLM generation options
 */
export interface GenerateOptions {
  /** Temperature for randomness (0-1, default: 0.0 for determinism) */
  temperature?: number;
  
  /** Maximum tokens to generate */
  maxTokens?: number;
  
  /** Stop sequences */
  stop?: string[];
  
  /** Top-p sampling */
  topP?: number;
  
  /** Top-k sampling */
  topK?: number;
  
  /** Random seed for reproducibility (default: 42) */
  seed?: number;
}

/**
 * Retry configuration for LLM generation (Iteration 6 Phase 2)
 */
export interface RetryConfig {
  /** Maximum retry attempts (default: 4) */
  maxAttempts?: number;
  
  /** Quality threshold score 0-1 (default: 0.6) */
  qualityThreshold?: number;
  
  /** Enable consensus voting across attempts (Phase 4 - optional) */
  enableConsensus?: boolean;
  
  /** Enable progressive prompting (Phase 3 - optional) */
  enableProgressivePrompting?: boolean;
}

/**
 * LLM response
 */
export interface LLMResponse {
  /** Generated text */
  text: string;
  
  /** Tokens used */
  tokensUsed?: number;
  
  /** Generation time in milliseconds */
  generationTime?: number;
  
  /** Model used */
  model?: string;
}

/**
 * Error thrown when parsing fails
 */
export class ParsingError extends Error {
  constructor(
    message: string,
    public readonly errorText: string,
    public readonly language: string
  ) {
    super(message);
    this.name = 'ParsingError';
  }
}

/**
 * Error thrown when LLM operation fails
 */
export class LLMError extends Error {
  constructor(
    message: string,
    public readonly statusCode?: number,
    public readonly retryable: boolean = true
  ) {
    super(message);
    this.name = 'LLMError';
  }
}

/**
 * Error thrown when analysis times out
 */
export class AnalysisTimeoutError extends Error {
  constructor(
    message: string,
    public readonly iteration: number,
    public readonly maxIterations: number
  ) {
    super(message);
    this.name = 'AnalysisTimeoutError';
  }
}

/**
 * Error thrown when input validation fails
 */
export class ValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ValidationError';
  }
}
