/**
 * Core type definitions for RCA Agent
 * 
 * This file contains all shared interfaces and types used throughout the system.
 * Following single source of truth principle for type definitions.
 */

/**
 * Project scope - whether error is from inside or outside the workspace
 */
export type ProjectScope = 'inside' | 'outside';

/**
 * Parsed error information extracted from error text
 */
export interface ParsedError {
  /** Type of error (e.g., 'lateinit', 'npe', 'build') */
  type: string;

  /** Full error message */
  message: string;

  /** File where error occurred */
  filePath: string;

  /** Line number where error occurred (1-indexed) */
  line: number;

  /** Programming language */
  language: 'kotlin' | 'java' | 'xml' | 'gradle' | 'proguard';

  /** Optional: Framework/library (e.g., 'compose', 'android') - added in Chunk 4.1 */
  framework?: string;

  /** Optional: Column number */
  column?: number;

  /** Optional: Stack trace frames */
  stackTrace?: StackFrame[];

  /** Optional: Additional metadata specific to error type */
  metadata?: Record<string, any>;
}

/**
 * Stack trace frame information
 */
export interface StackFrame {
  /** File path */
  file: string;

  /** Line number */
  line: number;

  /** Function/method name */
  function?: string;

  /** Class name */
  className?: string;
}

/**
 * Root Cause Analysis result
 */
export interface RCAResult {
  /** Original error message */
  error: string;

  /** Identified root cause */
  rootCause: string;

  /** Step-by-step fix guidelines */
  fixGuidelines: string[];

  /** Confidence score (0-1) */
  confidence: number;

  /** Optional: Number of iterations taken (added in Chunk 2.4) */
  iterations?: number;

  /** Optional: Tools used during analysis (added in Chunk 2.4) */
  toolsUsed?: string[];

  /** Optional: Related code snippets */
  codeContext?: string;

  /** Optional: Similar past errors */
  similarErrors?: string[];

  /** Optional: Generated code fix with diff (added in Chunk 5) */
  codeFix?: CodeFix;
}

/**
 * Generated code fix with diff information (Chunk 5: Fix Generator)
 */
export interface CodeFix {
  /** File being fixed */
  filePath: string;

  /** Line number where fix applies */
  line: number;

  /** Original code (before fix) */
  originalCode: string;

  /** Fixed code (after fix) */
  fixedCode: string;

  /** Formatted diff (markdown or unified) */
  diff: string;

  /** Explanation of what changed and why */
  explanation: string;

  /** Confidence score (0-100) */
  confidence: number;

  /** Whether fix is syntactically valid */
  syntaxValid: boolean;

  /** Optional: Additional files that need changes */
  relatedFiles?: RelatedFileFix[];
}

/**
 * Fix for related files (e.g., Gradle + Kotlin)
 */
export interface RelatedFileFix {
  filePath: string;
  line: number;
  originalCode: string;
  fixedCode: string;
  explanation: string;
}

/**
 * Agent state during analysis
 * Used for tracking progress and enabling checkpoint/resume
 */
export interface AgentState {
  /** Current iteration number */
  iteration: number;

  /** Maximum iterations allowed */
  maxIterations: number;

  /** Start time (timestamp) */
  startTime: number;

  /** Timeout in milliseconds */
  timeout: number;

  /** Analysis mode */
  mode: 'standard' | 'educational' | 'fast';

  /** Thoughts generated by agent */
  thoughts: string[];

  /** Actions taken (tool calls) */
  actions: ToolCall[];

  /** Observations from tool executions */
  observations: string[];

  /** Current hypothesis */
  hypothesis: string | null;

  /** Identified root cause */
  rootCause: string | null;

  /** Whether analysis has converged */
  converged: boolean;

  /** Error being analyzed */
  error: ParsedError;

  /** Optional: File content at error location (added in Chunk 1.4) */
  fileContent?: string | null;
}

/**
 * Tool call made by agent
 */
export interface ToolCall {
  /** Tool name */
  tool: string;

  /** Parameters passed to tool */
  parameters: Record<string, any>;

  /** Timestamp when tool was called */
  timestamp: number;

  /** Optional: Result of tool execution */
  result?: any;

  /** Optional: Error if tool failed */
  error?: string;
}

/**
 * LLM generation options
 */
export interface GenerateOptions {
  /** Temperature for randomness (0-1, default: 0.0 for determinism) */
  temperature?: number;

  /** Maximum tokens to generate */
  maxTokens?: number;

  /** Stop sequences */
  stop?: string[];

  /** Top-p sampling */
  topP?: number;

  /** Top-k sampling */
  topK?: number;

  /** Random seed for reproducibility (default: 42) */
  seed?: number;
}

/**
 * Retry configuration for LLM generation (Iteration 6 Phase 2)
 */
export interface RetryConfig {
  /** Maximum retry attempts (default: 4) */
  maxAttempts?: number;

  /** Quality threshold score 0-1 (default: 0.6) */
  qualityThreshold?: number;

  /** Enable consensus voting across attempts (Phase 4 - optional) */
  enableConsensus?: boolean;

  /** Enable progressive prompting (Phase 3 - optional) */
  enableProgressivePrompting?: boolean;
}

/**
 * LLM response
 */
export interface LLMResponse {
  /** Generated text */
  text: string;

  /** Tokens used */
  tokensUsed?: number;

  /** Generation time in milliseconds */
  generationTime?: number;

  /** Model used */
  model?: string;
}

/**
 * Error thrown when parsing fails
 */
export class ParsingError extends Error {
  constructor(
    message: string,
    public readonly errorText: string,
    public readonly language: string
  ) {
    super(message);
    this.name = 'ParsingError';
  }
}

export { AppError, ServiceError, LLMError, ValidationError, TimeoutError } from './errors/AppErrors';

/**
 * Error thrown when analysis times out
 */
export class AnalysisTimeoutError extends Error {
  constructor(
    message: string,
    public readonly iteration: number,
    public readonly maxIterations: number
  ) {
    super(message);
    this.name = 'AnalysisTimeoutError';
  }
}

// ============================================================================
// Conversational RCA Types (Phase 1)
// ============================================================================

/**
 * View types in the RCA application
 */
export type ViewType = 'dashboard' | 'errors' | 'analyze' | 'history' | 'agent' | 'fixes' | 'metrics';

/**
 * Message intent classification
 */
export type MessageIntent =
  | 'clarification'          // User asking for clarification of concept/term
  | 'explanation'            // User asking why something happened or was chosen
  | 'detail_request'         // User requesting more information/details
  | 'refinement'             // User providing correction/constraint for analysis
  | 'alternative'            // User asking for different solutions
  | 'correction'             // User stating something is wrong
  | 'positive_feedback'      // User indicating success
  | 'negative_feedback'      // User indicating failure
  | 'partial_feedback'       // Mixed feedback
  | 'new_analysis'           // User requesting new analysis
  | 'related_issue'          // User mentioning similar problem
  | 'agent_clarification'    // Agent asking for clarification (Phase 4)
  | 'clarification_answer'   // User answering agent's clarification (Phase 4)
  | 'refined_analysis'       // Refined analysis after clarification (Phase 4)
  | 'agent_suggestion'       // Agent providing suggestion
  | 'followup'               // General follow-up question
  | 'feedback'               // General user feedback
  | 'general';               // General conversation

/**
 * Conversation context - view-specific information
 */
export interface ConversationContext {
  /** Current view type */
  viewType: ViewType;

  /** Current route path */
  route: string;

  /** Timestamp when context was created/updated */
  timestamp: number;

  /** Optional: Active RCA result being discussed */
  activeRcaId?: string;

  /** Optional: Active error being discussed */
  activeErrorId?: string;

  /** Optional: Error type being discussed */
  errorType?: string;

  /** Optional: Last user message in conversation */
  lastUserMessage?: ConversationMessage;

  /** Optional: Additional context data */
  metadata?: Record<string, any>;
}

/**
 * Conversation session
 */
export interface ConversationSession {
  /** Unique session ID */
  id: string;

  /** Optional: Associated RCA result ID */
  rcaId?: string;

  /** When session was created */
  createdAt: Date;

  /** Last update time */
  updatedAt: Date;

  /** Session status */
  status: 'active' | 'paused' | 'completed';

  /** All messages in session */
  messages: ConversationMessage[];

  /** Session metadata */
  metadata: {
    /** Total message count */
    messageCount: number;

    /** Confidence evolution over conversation */
    confidenceEvolution: number[];

    /** Number of refinement iterations */
    refinementCount: number;

    /** Views visited during this conversation */
    viewsVisited: ViewType[];
  };
}

/**
 * Individual conversation message
 */
export interface ConversationMessage {
  /** Unique message ID */
  id: string;

  /** Session this message belongs to */
  sessionId: string;

  /** Message sender role */
  role: 'user' | 'assistant' | 'system';

  /** Message content */
  content: string;

  /** When message was created */
  timestamp: Date;

  /** Message delivery status */
  status?: 'sending' | 'sent' | 'failed';

  /** Optional: Message metadata */
  metadata?: {
    /** Classified intent */
    intent?: MessageIntent;

    /** Confidence score for assistant messages */
    confidence?: number;

    /** Tools used to generate this message */
    toolsUsed?: string[];

    /** Processing time in milliseconds */
    processingTime?: number;

    /** Context at time of message */
    context?: ConversationContext;

    /** Phase 3: Analysis delta for refinement messages */
    delta?: AnalysisDelta;

    /** Phase 4: Clarification questions from agent */
    clarificationQuestions?: ClarificationQuestion[];

    /** Phase 4: User's clarification answers */
    clarificationAnswers?: ClarificationAnswer[];

    /** Phase 4: Refined analysis after clarification */
    refinedAnalysis?: RootCauseAnalysis;

    /** Error message if processing failed */
    error?: string;
  };
}

/**
 * Compressed conversation context for long conversations
 */
export interface CompressedContext {
  /** Session ID */
  sessionId: string;

  /** Summarized conversation history */
  summary: string;

  /** Key points from conversation */
  keyPoints: string[];

  /** Important decisions made */
  decisions: string[];

  /** When compression was created */
  compressedAt: Date;

  /** Number of messages compressed */
  messageCount: number;
}

// ============================================================================
// Phase 3: Iterative Refinement Types
// ============================================================================

/**
 * Root Cause Analysis with full refinement tracking
 */
export interface RootCauseAnalysis {
  /** Unique RCA identifier */
  rcaId: string;

  /** Associated error log ID */
  errorLogId: string;

  /** Identified root cause */
  rootCause: string;

  /** Error category */
  category: string;

  /** Affected files with relevance scores */
  affectedFiles: AffectedFile[];

  /** Confidence score (0-100) */
  confidence: number;

  /** Suggested fix details */
  suggestedFix: Record<string, any>;

  /** When analysis was generated */
  generatedAt: Date;

  /** Model version used */
  modelVersion: string;

  /** Number of times this analysis has been refined */
  refinementCount: number;

  /** Optional: Previous version ID for version tracking */
  previousVersionId?: string;
}

/**
 * Affected file in analysis
 */
export interface AffectedFile {
  /** File path */
  filePath: string;

  /** Line numbers affected */
  lineNumbers: number[];

  /** Reason why this file is affected */
  reason: string;

  /** Relevance score (0-1) */
  relevanceScore: number;
}

/**
 * Result from refining an analysis
 */
export interface RefinementResult {
  /** Original analysis before refinement */
  originalAnalysis: RootCauseAnalysis;

  /** Refined analysis after applying user context */
  refinedAnalysis: RootCauseAnalysis;

  /** Delta between versions */
  delta: AnalysisDelta;

  /** Explanation of why changes were made */
  reasoning: string;

  /** Change in confidence score */
  confidenceChange: number;
}

/**
 * Delta between two analysis versions
 */
export interface AnalysisDelta {
  /** Whether root cause text changed */
  rootCauseChanged: boolean;

  /** File changes */
  filesChanged: FileChange[];

  /** Confidence change amount */
  confidenceChange: number;

  /** Before/after snapshots */
  changes: {
    before: AnalysisSnapshot;
    after: AnalysisSnapshot;
  };

  /** Explanation of what changed */
  reasoning: string;
}

/**
 * Snapshot of analysis at a point in time
 */
export interface AnalysisSnapshot {
  /** Root cause at this point */
  rootCause: string;

  /** Primary affected file */
  primaryFile: string;

  /** Confidence at this point */
  confidence: number;
}

/**
 * File change in delta
 */
export interface FileChange {
  /** Type of change */
  type: 'added' | 'removed' | 'unchanged' | 'modified';

  /** File path */
  filePath: string;

  /** Old relevance score (if existed) */
  oldRelevance?: number;

  /** New relevance score (if exists) */
  newRelevance?: number;
}

/**
 * Confidence tracking over time
 */
export interface ConfidenceEvolution {
  /** RCA identifier */
  rcaId: string;

  /** Confidence history */
  history: ConfidencePoint[];

  /** Overall trend (increasing/decreasing/stable) */
  trend: 'increasing' | 'decreasing' | 'stable';

  /** Initial confidence */
  initialConfidence: number;

  /** Current confidence */
  currentConfidence: number;

  /** Net change */
  netChange: number;
}

/**
 * Single confidence data point
 */
export interface ConfidencePoint {
  /** Timestamp */
  timestamp: Date;

  /** Confidence value (0-100) */
  confidence: number;

  /** Reason for change */
  reason: string;

  /** Associated message ID */
  messageId?: string;
}

// ============================================================================
// Phase 4: Agent-Initiated Clarification Types
// ============================================================================

/**
 * Uncertainty report from analysis
 */
export interface UncertaintyReport {
  /** Whether uncertainty was detected */
  hasUncertainty: boolean;

  /** Detected uncertainty signals */
  signals: UncertaintySignal[];

  /** Overall severity level */
  overallSeverity: 'low' | 'medium' | 'high';

  /** Whether agent should ask for clarification */
  shouldAskClarification: boolean;
}

/**
 * Individual uncertainty signal
 */
export interface UncertaintySignal {
  /** Type of uncertainty detected */
  type: 'low_confidence' | 'ambiguous_files' | 'missing_context' | 'unclear_intent';

  /** Severity of this signal */
  severity: 'low' | 'medium' | 'high';

  /** Human-readable description */
  description: string;

  /** Suggested question to resolve uncertainty */
  suggestedQuestion: string;
}

/**
 * Clarification question generated by agent
 */
export interface ClarificationQuestion {
  /** Unique question identifier */
  questionId: string;

  /** Type of question */
  type: 'open_ended' | 'multiple_choice' | 'yes_no' | 'file_selection';

  /** Question prompt text */
  prompt: string;

  /** Options for multiple choice/selection questions */
  options?: ClarificationOption[];

  /** Context explaining why asking */
  context: string;
}

/**
 * Option for multiple choice questions
 */
export interface ClarificationOption {
  /** Option value */
  value: string;

  /** Display label */
  label: string;

  /** Optional description */
  description?: string;
}

/**
 * User's answer to clarification question
 */
export interface ClarificationAnswer {
  /** Question ID this answers */
  questionId: string;

  /** Answer value(s) */
  answer: string | string[];

  /** When answer was provided */
  timestamp: Date;
}

/**
 * Result of clarification analysis
 */
export interface ClarificationResult {
  /** Whether clarification is needed */
  needsClarification: boolean;

  /** Questions to ask user */
  questions: ClarificationQuestion[];

  /** Reason for asking (or not asking) */
  reason: string;

  /** Optional: underlying uncertainty report */
  uncertaintyReport?: UncertaintyReport;
}
